import { Language } from './types';

export const OFFLINE_THRESHOLD = 2 * 60 * 1000; // 2 minutes in milliseconds

export const translations: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    'login.title': 'Welcome to Devices Cloud',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.button': 'Login',
    'login.authenticating': 'Authenticating...',
    'login.error': 'Invalid email or password.',
    'login.fetchError': 'Could not authenticate. Please check the console.',
    'header.title': 'Devices Cloud',
    'header.logout': 'Logout',
    'sidebar.companies': 'Companies',
    'sidebar.addCompany': 'Add Company',
    'sidebar.deviceCount': 'Total Devices',
    'dashboard.selectCompany': 'Select a company from the sidebar to view its devices.',
    'dashboard.noDevices': 'No devices in this company yet.',
    'dashboard.addDevice': 'Add Device',
    'dashboard.devices': 'Devices',
    'device.offline': 'Offline',
    'device.lastUpdate': 'Last update',
    'device.viewJson': 'View Raw JSON',
    'modal.addCompany.title': 'Create New Company',
    'modal.addCompany.name': 'Company Name',
    'modal.addCompany.limit': 'You have reached your company limit.',
    'modal.addDevice.title': 'Add New Device',
    'modal.addDevice.limit': 'You have reached your total device limit.',
    'modal.addDevice.step1': 'Device Info',
    'modal.addDevice.step2': 'Protocol',
    'modal.addDevice.step3': 'Data & Widgets',
    'modal.addDevice.name': 'Device Name',
    'modal.addDevice.protocol': 'Communication Protocol',
    'modal.addDevice.http.url': 'Endpoint URL',
    'modal.addDevice.mqtt.broker': 'Broker Address',
    'modal.addDevice.mqtt.topic': 'Topic',
    'modal.addDevice.ftp.server': 'Server Address',
    'modal.addDevice.ftp.path': 'File Path',
    'modal.addDevice.sampleJson': 'Paste a sample JSON payload from your device',
    'modal.addDevice.parseError': 'Invalid JSON format',
    'modal.addDevice.widgets': 'Widgets',
    'modal.addDevice.addWidget': 'Add Widget',
    'modal.addDevice.widget.name': 'Widget Name',
    'modal.addDevice.widget.type': 'Widget Type',
    'modal.addDevice.widget.dataKey': 'Data Key from JSON',
    'modal.addDevice.widget.unit': 'Unit (e.g., °C, %, ppm)',
    'modal.addDevice.widget.noKeys': 'Parse JSON to see available keys.',
    'modal.jsonViewer.title': 'Last Received Data',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.create': 'Create',
    'common.next': 'Next',
    'common.back': 'Back',
    'common.finish': 'Finish',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'widget.tank': 'Tank Level',
    'widget.switch': 'On/Off Switch',
    'widget.gauge': 'Gauge',
    'widget.value': 'Simple Value',
  },
  [Language.PT]: {
    'login.title': 'Bem-vindo ao Devices Cloud',
    'login.email': 'E-mail',
    'login.password': 'Senha',
    'login.button': 'Entrar',
    'login.authenticating': 'Autenticando...',
    'login.error': 'E-mail ou senha inválidos.',
    'login.fetchError': 'Não foi possível autenticar. Verifique o console.',
    'header.title': 'Devices Cloud',
    'header.logout': 'Sair',
    'sidebar.companies': 'Empresas',
    'sidebar.addCompany': 'Adicionar Empresa',
    'sidebar.deviceCount': 'Total de Dispositivos',
    'dashboard.selectCompany': 'Selecione uma empresa na barra lateral para ver seus dispositivos.',
    'dashboard.noDevices': 'Nenhum dispositivo nesta empresa ainda.',
    'dashboard.addDevice': 'Adicionar Dispositivo',
    'dashboard.devices': 'Dispositivos',
    'device.offline': 'Offline',
    'device.lastUpdate': 'Última atualização',
    'device.viewJson': 'Ver JSON Bruto',
    'modal.addCompany.title': 'Criar Nova Empresa',
    'modal.addCompany.name': 'Nome da Empresa',
    'modal.addCompany.limit': 'Você atingiu seu limite de empresas.',
    'modal.addDevice.title': 'Adicionar Novo Dispositivo',
    'modal.addDevice.limit': 'Você atingiu seu limite total de dispositivos.',
    'modal.addDevice.step1': 'Informações do Dispositivo',
    'modal.addDevice.step2': 'Protocolo',
    'modal.addDevice.step3': 'Dados e Widgets',
    'modal.addDevice.name': 'Nome do Dispositivo',
    'modal.addDevice.protocol': 'Protocolo de Comunicação',
    'modal.addDevice.http.url': 'URL do Endpoint',
    'modal.addDevice.mqtt.broker': 'Endereço do Broker',
    'modal.addDevice.mqtt.topic': 'Tópico',
    'modal.addDevice.ftp.server': 'Endereço do Servidor',
    'modal.addDevice.ftp.path': 'Caminho do Arquivo',
    'modal.addDevice.sampleJson': 'Cole um exemplo de payload JSON do seu dispositivo',
    'modal.addDevice.parseError': 'Formato JSON inválido',
    'modal.addDevice.widgets': 'Widgets',
    'modal.addDevice.addWidget': 'Adicionar Widget',
    'modal.addDevice.widget.name': 'Nome do Widget',
    'modal.addDevice.widget.type': 'Tipo de Widget',
    'modal.addDevice.widget.dataKey': 'Chave de Dados do JSON',
    'modal.addDevice.widget.unit': 'Unidade (ex: °C, %, ppm)',
    'modal.addDevice.widget.noKeys': 'Analise o JSON para ver as chaves disponíveis.',
    'modal.jsonViewer.title': 'Últimos Dados Recebidos',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.create': 'Criar',
    'common.next': 'Próximo',
    'common.back': 'Voltar',
    'common.finish': 'Finalizar',
    'common.delete': 'Excluir',
    'common.close': 'Fechar',
    'widget.tank': 'Nível do Tanque',
    'widget.switch': 'Interruptor On/Off',
    'widget.gauge': 'Medidor',
    'widget.value': 'Valor Simples',
  },
  [Language.ES]: {
    'login.title': 'Bienvenido a Devices Cloud',
    'login.email': 'Correo Electrónico',
    'login.password': 'Contraseña',
    'login.button': 'Iniciar Sesión',
    'login.authenticating': 'Autenticando...',
    'login.error': 'Correo o contraseña no válidos.',
    'login.fetchError': 'No se pudo autenticar. Revisa la consola.',
    'header.title': 'Devices Cloud',
    'header.logout': 'Cerrar Sesión',
    'sidebar.companies': 'Empresas',
    'sidebar.addCompany': 'Añadir Empresa',
    'sidebar.deviceCount': 'Dispositivos Totales',
    'dashboard.selectCompany': 'Seleccione una empresa de la barra lateral para ver sus dispositivos.',
    'dashboard.noDevices': 'Aún no hay dispositivos en esta empresa.',
    'dashboard.addDevice': 'Añadir Dispositivo',
    'dashboard.devices': 'Dispositivos',
    'device.offline': 'Desconectado',
    'device.lastUpdate': 'Última actualización',
    'device.viewJson': 'Ver JSON Crudo',
    'modal.addCompany.title': 'Crear Nueva Empresa',
    'modal.addCompany.name': 'Nombre de la Empresa',
    'modal.addCompany.limit': 'Ha alcanzado su límite de empresas.',
    'modal.addDevice.title': 'Añadir Nuevo Dispositivo',
    'modal.addDevice.limit': 'Ha alcanzado su límite total de dispositivos.',
    'modal.addDevice.step1': 'Info del Dispositivo',
    'modal.addDevice.step2': 'Protocolo',
    'modal.addDevice.step3': 'Datos y Widgets',
    'modal.addDevice.name': 'Nombre del Dispositivo',
    'modal.addDevice.protocol': 'Protocolo de Comunicación',
    'modal.addDevice.http.url': 'URL del Endpoint',
    'modal.addDevice.mqtt.broker': 'Dirección del Broker',
    'modal.addDevice.mqtt.topic': 'Tema',
    'modal.addDevice.ftp.server': 'Dirección del Servidor',
    'modal.addDevice.ftp.path': 'Ruta del Archivo',
    'modal.addDevice.sampleJson': 'Pegue una carga útil JSON de muestra de su dispositivo',
    'modal.addDevice.parseError': 'Formato JSON inválido',
    'modal.addDevice.widgets': 'Widgets',
    'modal.addDevice.addWidget': 'Añadir Widget',
    'modal.addDevice.widget.name': 'Nombre del Widget',
    'modal.addDevice.widget.type': 'Tipo de Widget',
    'modal.addDevice.widget.dataKey': 'Clave de Datos del JSON',
    'modal.addDevice.widget.unit': 'Unidad (ej: °C, %, ppm)',
    'modal.addDevice.widget.noKeys': 'Analiza el JSON para ver las claves disponibles.',
    'modal.jsonViewer.title': 'Últimos Datos Recibidos',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.create': 'Crear',
    'common.next': 'Siguiente',
    'common.back': 'Atrás',
    'common.finish': 'Finalizar',
    'common.delete': 'Eliminar',
    'common.close': 'Cerrar',
    'widget.tank': 'Nivel del Tanque',
    'widget.switch': 'Interruptor On/Off',
    'widget.gauge': 'Medidor',
    'widget.value': 'Valor Simple',
  },
};